GET http://localhost:3000/carritos

#####

GET http://localhost:3000/carritos/18a76292-4d2f-40f1-9870-5bdcefe1b4b9

#####
POST http://localhost:3000/carritos
Content-Type: application/json

{
    "estado": "pagado"
}

######

PUT http://localhost:3000/carritos/878cfdac-d3c6-4e6d-884e-3e1c6ec7fe70
Content-Type: application/json

{
    "estado": "cerrado"
    
}


######

DELETE http://localhost:3000/carritos/862ad554-16b4-4448-9193-c032f98275f5