GET http://localhost:3000/productos

#####

GET http://localhost:3000/productos/35676


#####
POST http://localhost:3000/productos
Content-Type: application/json

{
    "nombre": "Producto de prueba",
    "codigo": "345676", 
    "genero": "Masculino",
    "precio_costo": 10000,
    "precio_venta": 15000,
    "stock_inicial": 10,
    "stock_minimo": 5,
    "proveedor": "Proveedor de prueba",
    "descripcion": "Producto de prueba para el sistema de inventario"
}

######

PUT http://localhost:3000/productos/101010
Content-Type: application/json

{
    "nombre": "nuevo productro",
    "codigo": "101010",
    "genero": "Masculino",
    "precio_costo": 10000,
    "precio_venta": 15000

}


######

DELETE http://localhost:3000/productos/101010
