GET http://localhost:3000/productos

#####

GET http://localhost:3000/productos/PRB001


#####
POST http://localhost:3000/productos
Content-Type: application/json

{
    "nombre": "jean de jeffry",
    "codigo": "2133", 
    "genero": "Masculino",
    "precio_costo": 10000,
    "precio_venta": 15000,
    "stock_inicial": 4,
    "stock_minimo": 5,
    "proveedor": "Proveedor de prueba",
    "descripcion": "Producto de prueba para el sistema de inventario"
}

######

PUT http://localhost:3000/productos/PRB001
Content-Type: application/json

{
    "nombre": "nuevo productro",
    "codigo": "PRB001",
    "genero": "Masculino",
    "precio_costo": 10000,
    "precio_venta": 15000

}


######

DELETE http://localhost:3000/productos/PRB001
